### ISSUE TITLE
Para romper el hielo con estos issues... "Títulos"

### ISSUE THREAD

**Issue by EugenioMuttio** [GloriAlmanza/Notas_metodos_numericos#6]

**Comment by EugenioMuttio** [comment]
Tengo la siguiente duda:

El formato de títulos y subtítulos de acuerdo a la escritura de obras en español se supone que llevan una letra mayúscula solamente al principio, como por ejemplo:

**Derivadas numéricas parciales**

En la escritura de obras en inglés tienen una regla en donde cada palabra lleva una mayúscula:

**Derivadas Numéricas Parciales**

Pero últimamente, quizá por la influencia de la escritura en inglés he visto que libros en español usan dicha regla.

En cuestión estética, como que si me gusta más que se vea una mayúscula en cada palabra (siempre y cuando no sean conectores "y", "o", etc...)

¿Pero como creen que sea vea mejor?

Saludos!

@jacobess @GloriAlmanza @sofigueroad

**Comment by jacobess** [comment]
A mi personalmente me late esa idea. Se ven bien con mayusculas iniciales!

**Comment by EugenioMuttio** [comment]
Entonces la damos por cerrada? Que opinan @GloriAlmanza @sofigueroad

**Comment by sofigueroad** [comment]
A mí también me gusta más cómo se ve cada palabra con mayúscula al inicio :)
