### ISSUE TITLE
Envie revision Sofia. Para practicar issues 

### ISSUE THREAD

**Issue by jacobess** [GloriAlmanza/Notas_metodos_numericos#7]
Mande commit sin incluir tus modificaciones subidas el dia de hoy. Por la noche lo re-checo. 

Saludos .  Cuando realizes las correcciones indicadas en el pdf de revision por favor dar por resuelto este issue.

**Comment by sofigueroad** [comment]
Ya hice todas las correcciones señaladas excepto lo de poner los tres dibujos (esto venía en la segunda corrección del capítulo 2, no estoy segura de dónde sacar los tres dibujos que solicitas, ya que en las notas de Nancy no viene ninguno, pero tú me indicas exactamente cómo deben de ser, por favor) y en efecto faltan imágenes y ecuaciones por lo cual unas oraciones están desligadas, pero estoy trabajando en ello.
¡Saludos!
